### ISSUE TITLE
GitHub Page not Found

### ISSUE THREAD

**Issue by nicksuch** [openlexington/openlexington.org#18]
Seeing a [Page Not Found error](http://cl.ly/image/2q1s1y0L2Q21) today. Did we make a change to the repository name (eg from openlexington.github.io to openlexington.org)? GitHub pages does some funny stuff sometimes.

**Comment by chaserx** [comment]
Yeah.... I fucked it up. Thought there would be magic.

**Comment by chaserx** [comment]
Everything should be back as it was.....
