### ISSUE TITLE
openlexington.org resolves to a GitHub 404

### ISSUE THREAD

**Issue by eeeschwartz** [openlexington/openlexington.org#23]
I'm looking into possible issues but wanted to flag here in case anyone already knows whattup.

**Comment by chaserx** [comment]
`Your page is having problems building: Validation failed: User must be a human, not an Organization`

**Comment by chaserx** [comment]
well looks like lives.openlexington.org is down too

**Comment by chaserx** [comment]
I wonder if we _have_ to change this to `openlexington.github.io` now

**Comment by chaserx** [comment]
I feel like we just mucked with this a few months ago.

**Comment by eeeschwartz** [comment]
I added a dummy file, pushed to the gh-pages branch, and the build fixed itself. Same story for lives.openlexington.org.

Not sure what was up :question: :grey_question: :octocat:
