### ISSUE TITLE
lex_underutil broken link in projects.html

### ISSUE THREAD

**Issue by bFraley** [openlexington/openlexington.org#26]
Is there a correct URL this should point to?

`<a href="http://openlexington.github.io/lex_underutil/" class="project-title">Lex_Underutil</a>
  <span class="description">Tilemill map of underutilized properties in Lexington, Kentucky  </span>`

**Comment by chaserx** [comment]
there's a problem with github pages where it wants the author to be a human and not an organization... perhaps @blakeshall can't look at lex_underutil and get it working again. 😁

**Comment by blakeshall** [comment]
It's fixed now. Looks like the github page disappeared but pushing an update caused it to be rebuilt.

**Comment by bFraley** [comment]
@blakeshall cool project!
