### ISSUE TITLE
projects.html - Format layout for improved UX readability

### ISSUE THREAD

**Issue by bFraley** [openlexington/openlexington.org#28]
What I have in mind is very simple. I'm assigning myself, and will post a screen shot here when ready.

**Comment by chaserx** [comment]
Cool. I'm open to any alternate design. 

Here's the master list of all Brigades for inspiration and reference: https://www.codeforamerica.org/join-us/volunteer-with-us/list-of-all-brigades

Many of them use some variant of a template. I'll drop those in below if I come across them. 

Also for reference here and #21 

https://github.com/CodeForPhilly/laddr
https://github.com/sfbrigade/sfbrigade.github.io

**Comment by bFraley** [comment]
Closing this as it was opened 2 years ago. Please contact me if more openlexington work is planned and this project is still looking for website / project contributions!
