### ISSUE TITLE
We need to update DNS to point at updated IPs for continued hosting on GitHub Pages

### ISSUE THREAD

**Issue by chaserx** [openlexington/openlexington.org#32]
<img width="773" alt="Screen Shot 2019-09-01 at 9 19 18 PM" src="https://user-images.githubusercontent.com/7292/64085035-469d8a80-ccfe-11e9-8657-895192c08591.png">

**Comment by chaserx** [comment]
see the settings in this repo for more.

**Comment by chaserx** [comment]
I think @nikolaiwarner owns the domain and but I think I've got DNS routed through some old account on DNSimple.

**Comment by chaserx** [comment]
I think I've got this solved. 

<img width="1247" alt="Screen Shot 2019-09-01 at 9 26 13 PM" src="https://user-images.githubusercontent.com/7292/64085195-2e7a3b00-ccff-11e9-817b-f3d0934e357e.png">

**Comment by chaserx** [comment]
settings on DNSimple do not seem to have an effect even after many hours later. 

<img width="1335" alt="Screen Shot 2019-09-02 at 12 42 58 PM" src="https://user-images.githubusercontent.com/7292/64127376-6923b800-cd7f-11e9-8524-40f7a89a03bf.png">

**Comment by chaserx** [comment]
Here's why

<img width="599" alt="Screen Shot 2019-09-02 at 12 53 23 PM" src="https://user-images.githubusercontent.com/7292/64127685-bc4a3a80-cd80-11e9-9abe-e72eddb9f0e5.png">

**Comment by chaserx** [comment]
this'll need to be solved by @nikolaiwarner i think

**Comment by nikolaiwarner** [comment]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/40796/64262637-61d5e900-cefc-11e9-968d-e94e608f418d.png">

**Comment by chaserx** [comment]
thank you @nikolaiwarner

**Comment by nikolaiwarner** [comment]
@chaserx ❤️
